### ISSUE TITLE
How to display results in html?

### ISSUE THREAD

**Issue by princebhatia09** [53ningen/Monita#2]
Like i want to display old and new html with color? Green yellow or red? How to do it?

**Comment by 53ningen** [comment]
@princebhatia09 
you mean you would like to send HTML diff like below to Amazon SNS Topic?

```diff
<ul>
+ <li>new article title</li>
- <li>deleted article title</li>
... 
```

Currently this app compares the MD5 hash[1] of the HTML source selected with the CSS selector specified in config file[2].

[1] https://github.com/53ningen/Monita/blob/master/src/detect_website_changes/app.py#L53-L88
[2] https://github.com/53ningen/Monita/blob/master/config.template.yaml#L45

But if you want to do so, pull requests or feature requests are a welcome.

**Comment by 53ningen** [comment]
If you really want this feature, please do not hesitate to reopen this issue.
